---
#Project setting
wordpress_sites: sashaunisex
wordpress_home_url: "http://95.85.2.66"
wordpress_home_url_non_http: "95.85.2.66"
wordpress_site_title: "{{ wordpress_sites }}"
remote_wordpress_dir: "{{ www_root }}/{{ wordpress_sites }}"
wordpress_git_url: git@git.sakema.net:hurma/healthy-boat.git

#MySQL setting
mysql_root_user: root
mysql_root_password: HHmhbXHISLn0UwOz

#WP admin setting
wordpress_admin_user: "admin"
wordpress_admin_user_pass: "4MyFXzFWHqYtXIGj"
wordpress_admin_email: "lettertosasha@gmail.com"

#WP DB setting
wordpress_db_name: "{{ wordpress_sites }}"
wordpress_db_user: "{{ wordpress_sites }}"
wordpress_db_user_pass: "C5hpDoWPXiYtCZQF"
wordpress_db_prefix: wp_

#Nginx setting
nginx_path: /etc/nginx

#mail
ssmtp_auth_user: "contact@healthyboat.ru"
ssmtp_auth_pass: "ZlACu6KoZkjoaGSYLMLmfAM1udTofsE"
